<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ChampionshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionshipRepository extends ModelRepository
{

    /**
     * @param int $teamId
     * @return array
     * @throws \Exception
     */
    public function findByTeam($teamId){
        $q = $this->createQueryBuilder('c')
            ->innerJoin('AppBundle\Entity\ChampionshipTeam', 'ct', 'WITH', 'c = ct.championship')
            ->innerJoin('AppBundle\Entity\Team', 't', 'WITH', 't = ct.team AND t.id = :id')
            ->groupBy('c.id')
            ->orderBy('c.name', 'ASC')
            ->orderBy('c.id', 'DESC')
            ->setParameter('id', $teamId);

        try {
            $championships = $q->getQuery()->getResult();
        } catch (NoResultException $e) {
            throw new \Exception(sprintf('Unable to filter table by like'), null, 0, $e);
        }
         return $championships;
    }

    /**
     * @param int $playerId
     * @return array
     * @throws \Exception
     */
    public function findByPlayer($playerId){
        $q = $this->createQueryBuilder('c')
            ->innerJoin('AppBundle\Entity\ChampionshipTeam', 'ct', 'WITH', 'c = ct.championship')
            ->innerJoin('AppBundle\Entity\Team', 't', 'WITH', 't = ct.team')
            ->innerJoin('AppBundle\Entity\TeamPlayer', 'tp', 'WITH', 't = tp.team')
            ->innerJoin('AppBundle\Entity\player', 'p', 'WITH', 'p = tp.player AND p.id = :id')
            ->groupBy('c.id')
            ->orderBy('c.name', 'ASC')
            ->orderBy('c.id', 'DESC')
            ->setParameter('id', $playerId);

        try {
            $championships = $q->getQuery()->getResult();
        } catch (NoResultException $e) {
            throw new \Exception(sprintf('Unable to filter found championship by player id'), null, 0, $e);
        }
        return $championships;
    }

}