<?php

namespace AppBundle\Repository;

/**
 * MatchPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
